pub mod config;
pub mod dept;
pub mod dict_item;
pub mod dict_type;
pub mod feature;
pub mod file;
pub mod file_folder;
pub mod gen_column;
pub mod gen_table;
pub mod id;
pub mod job;
pub mod job_log;
pub mod menu;
pub mod message;
pub mod message_receiver;
pub mod notice;
pub mod operation_log;
pub mod package;
pub mod package_feature;
pub mod param;
pub mod post;
pub mod role;
pub mod role_dept;
pub mod role_menu;
pub mod tenant;
pub mod tenant_feature;
pub mod user;
pub mod user_role;

pub mod prelude {
    pub use super::config::Entity as Config;
    pub use super::dept::Entity as Dept;
    pub use super::dict_item::Entity as DictItem;
    pub use super::dict_type::Entity as DictType;
    pub use super::feature::Entity as Feature;
    pub use super::file::Entity as File;
    pub use super::file_folder::Entity as FileFolder;
    pub use super::gen_column::Entity as GenColumn;
    pub use super::gen_table::Entity as GenTable;
    pub use super::job::Entity as Job;
    pub use super::job_log::Entity as JobLog;
    pub use super::menu::Entity as Menu;
    pub use super::message::Entity as Message;
    pub use super::message_receiver::Entity as MessageReceiver;
    pub use super::notice::Entity as Notice;
    pub use super::operation_log::Entity as OperationLog;
    pub use super::package::Entity as Package;
    pub use super::package_feature::Entity as PackageFeature;
    pub use super::param::Entity as Param;
    pub use super::post::Entity as Post;
    pub use super::role::Entity as Role;
    pub use super::role_dept::Entity as RoleDept;
    pub use super::role_menu::Entity as RoleMenu;
    pub use super::tenant::Entity as Tenant;
    pub use super::tenant_feature::Entity as TenantFeature;
    pub use super::user::Entity as User;
    pub use super::user_role::Entity as UserRole;
}
