[package]
name = "common"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
axum.workspace = true
jsonwebtoken.workspace = true
argon2.workspace = true
chrono.workspace = true
utoipa.workspace = true
config.workspace = true
deadpool-redis.workspace = true
tracing.workspace = true
sea-orm.workspace = true
casbin.workspace = true
uuid.workspace = true
