[package]
name = "service"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
common.workspace = true
entity.workspace = true
sea-orm.workspace = true
casbin.workspace = true
deadpool-redis.workspace = true
validator.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
anyhow.workspace = true
tokio.workspace = true
