/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTenantsRouteImport } from './routes/_app/tenants'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRolesRouteImport } from './routes/_app/roles'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPostsRouteImport } from './routes/_app/posts'
import { Route as AppParamsRouteImport } from './routes/_app/params'
import { Route as AppNoticesRouteImport } from './routes/_app/notices'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppMenusRouteImport } from './routes/_app/menus'
import { Route as AppLogsRouteImport } from './routes/_app/logs'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppGenRouteImport } from './routes/_app/gen'
import { Route as AppFilesRouteImport } from './routes/_app/files'
import { Route as AppDictRouteImport } from './routes/_app/dict'
import { Route as AppDeptsRouteImport } from './routes/_app/depts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsRoute = AppPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AppRoute,
} as any)
const AppParamsRoute = AppParamsRouteImport.update({
  id: '/params',
  path: '/params',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMenusRoute = AppMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppGenRoute = AppGenRouteImport.update({
  id: '/gen',
  path: '/gen',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppDictRoute = AppDictRouteImport.update({
  id: '/dict',
  path: '/dict',
  getParentRoute: () => AppRoute,
} as any)
const AppDeptsRoute = AppDeptsRouteImport.update({
  id: '/depts',
  path: '/depts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/depts': typeof AppDeptsRoute
  '/dict': typeof AppDictRoute
  '/files': typeof AppFilesRoute
  '/gen': typeof AppGenRoute
  '/jobs': typeof AppJobsRoute
  '/logs': typeof AppLogsRoute
  '/menus': typeof AppMenusRoute
  '/messages': typeof AppMessagesRoute
  '/notices': typeof AppNoticesRoute
  '/params': typeof AppParamsRoute
  '/posts': typeof AppPostsRoute
  '/profile': typeof AppProfileRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/tenants': typeof AppTenantsRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/depts': typeof AppDeptsRoute
  '/dict': typeof AppDictRoute
  '/files': typeof AppFilesRoute
  '/gen': typeof AppGenRoute
  '/jobs': typeof AppJobsRoute
  '/logs': typeof AppLogsRoute
  '/menus': typeof AppMenusRoute
  '/messages': typeof AppMessagesRoute
  '/notices': typeof AppNoticesRoute
  '/params': typeof AppParamsRoute
  '/posts': typeof AppPostsRoute
  '/profile': typeof AppProfileRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/tenants': typeof AppTenantsRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/depts': typeof AppDeptsRoute
  '/_app/dict': typeof AppDictRoute
  '/_app/files': typeof AppFilesRoute
  '/_app/gen': typeof AppGenRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/menus': typeof AppMenusRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/notices': typeof AppNoticesRoute
  '/_app/params': typeof AppParamsRoute
  '/_app/posts': typeof AppPostsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tenants': typeof AppTenantsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/depts'
    | '/dict'
    | '/files'
    | '/gen'
    | '/jobs'
    | '/logs'
    | '/menus'
    | '/messages'
    | '/notices'
    | '/params'
    | '/posts'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/tenants'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/depts'
    | '/dict'
    | '/files'
    | '/gen'
    | '/jobs'
    | '/logs'
    | '/menus'
    | '/messages'
    | '/notices'
    | '/params'
    | '/posts'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/tenants'
    | '/users'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/depts'
    | '/_app/dict'
    | '/_app/files'
    | '/_app/gen'
    | '/_app/jobs'
    | '/_app/logs'
    | '/_app/menus'
    | '/_app/messages'
    | '/_app/notices'
    | '/_app/params'
    | '/_app/posts'
    | '/_app/profile'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/tenants'
    | '/_app/users'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants': {
      id: '/_app/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts': {
      id: '/_app/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AppPostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/params': {
      id: '/_app/params'
      path: '/params'
      fullPath: '/params'
      preLoaderRoute: typeof AppParamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notices': {
      id: '/_app/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menus': {
      id: '/_app/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof AppMenusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gen': {
      id: '/_app/gen'
      path: '/gen'
      fullPath: '/gen'
      preLoaderRoute: typeof AppGenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dict': {
      id: '/_app/dict'
      path: '/dict'
      fullPath: '/dict'
      preLoaderRoute: typeof AppDictRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/depts': {
      id: '/_app/depts'
      path: '/depts'
      fullPath: '/depts'
      preLoaderRoute: typeof AppDeptsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDeptsRoute: typeof AppDeptsRoute
  AppDictRoute: typeof AppDictRoute
  AppFilesRoute: typeof AppFilesRoute
  AppGenRoute: typeof AppGenRoute
  AppJobsRoute: typeof AppJobsRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMenusRoute: typeof AppMenusRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNoticesRoute: typeof AppNoticesRoute
  AppParamsRoute: typeof AppParamsRoute
  AppPostsRoute: typeof AppPostsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTenantsRoute: typeof AppTenantsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDeptsRoute: AppDeptsRoute,
  AppDictRoute: AppDictRoute,
  AppFilesRoute: AppFilesRoute,
  AppGenRoute: AppGenRoute,
  AppJobsRoute: AppJobsRoute,
  AppLogsRoute: AppLogsRoute,
  AppMenusRoute: AppMenusRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNoticesRoute: AppNoticesRoute,
  AppParamsRoute: AppParamsRoute,
  AppPostsRoute: AppPostsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTenantsRoute: AppTenantsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
