/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsersRouteRouteImport } from './routes/_app/users/route'
import { Route as AppTenantsRouteRouteImport } from './routes/_app/tenants/route'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppRolesRouteRouteImport } from './routes/_app/roles/route'
import { Route as AppProfileRouteRouteImport } from './routes/_app/profile/route'
import { Route as AppPostsRouteRouteImport } from './routes/_app/posts/route'
import { Route as AppParamsRouteRouteImport } from './routes/_app/params/route'
import { Route as AppOnlineRouteRouteImport } from './routes/_app/online/route'
import { Route as AppNoticesRouteRouteImport } from './routes/_app/notices/route'
import { Route as AppMonitorRouteRouteImport } from './routes/_app/monitor/route'
import { Route as AppMessagesRouteRouteImport } from './routes/_app/messages/route'
import { Route as AppMenusRouteRouteImport } from './routes/_app/menus/route'
import { Route as AppLogsRouteRouteImport } from './routes/_app/logs/route'
import { Route as AppJobsRouteRouteImport } from './routes/_app/jobs/route'
import { Route as AppGenRouteRouteImport } from './routes/_app/gen/route'
import { Route as AppFilesRouteRouteImport } from './routes/_app/files/route'
import { Route as AppDictRouteRouteImport } from './routes/_app/dict/route'
import { Route as AppDeptsRouteRouteImport } from './routes/_app/depts/route'
import { Route as AppDictIndexRouteImport } from './routes/_app/dict/index'
import { Route as AppDictItemsRouteImport } from './routes/_app/dict/items'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersRouteRoute = AppUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTenantsRouteRoute = AppTenantsRouteRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesRouteRoute = AppRolesRouteRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRouteRoute = AppProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPostsRouteRoute = AppPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppParamsRouteRoute = AppParamsRouteRouteImport.update({
  id: '/params',
  path: '/params',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnlineRouteRoute = AppOnlineRouteRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNoticesRouteRoute = AppNoticesRouteRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMonitorRouteRoute = AppMonitorRouteRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMessagesRouteRoute = AppMessagesRouteRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMenusRouteRoute = AppMenusRouteRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLogsRouteRoute = AppLogsRouteRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppJobsRouteRoute = AppJobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGenRouteRoute = AppGenRouteRouteImport.update({
  id: '/gen',
  path: '/gen',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFilesRouteRoute = AppFilesRouteRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDictRouteRoute = AppDictRouteRouteImport.update({
  id: '/dict',
  path: '/dict',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDeptsRouteRoute = AppDeptsRouteRouteImport.update({
  id: '/depts',
  path: '/depts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDictIndexRoute = AppDictIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDictRouteRoute,
} as any)
const AppDictItemsRoute = AppDictItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppDictRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRouteRoute
  '/depts': typeof AppDeptsRouteRoute
  '/dict': typeof AppDictRouteRouteWithChildren
  '/files': typeof AppFilesRouteRoute
  '/gen': typeof AppGenRouteRoute
  '/jobs': typeof AppJobsRouteRoute
  '/logs': typeof AppLogsRouteRoute
  '/menus': typeof AppMenusRouteRoute
  '/messages': typeof AppMessagesRouteRoute
  '/monitor': typeof AppMonitorRouteRoute
  '/notices': typeof AppNoticesRouteRoute
  '/online': typeof AppOnlineRouteRoute
  '/params': typeof AppParamsRouteRoute
  '/posts': typeof AppPostsRouteRoute
  '/profile': typeof AppProfileRouteRoute
  '/roles': typeof AppRolesRouteRoute
  '/settings': typeof AppSettingsRouteRoute
  '/tenants': typeof AppTenantsRouteRoute
  '/users': typeof AppUsersRouteRoute
  '/dict/items': typeof AppDictItemsRoute
  '/dict/': typeof AppDictIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRouteRoute
  '/depts': typeof AppDeptsRouteRoute
  '/files': typeof AppFilesRouteRoute
  '/gen': typeof AppGenRouteRoute
  '/jobs': typeof AppJobsRouteRoute
  '/logs': typeof AppLogsRouteRoute
  '/menus': typeof AppMenusRouteRoute
  '/messages': typeof AppMessagesRouteRoute
  '/monitor': typeof AppMonitorRouteRoute
  '/notices': typeof AppNoticesRouteRoute
  '/online': typeof AppOnlineRouteRoute
  '/params': typeof AppParamsRouteRoute
  '/posts': typeof AppPostsRouteRoute
  '/profile': typeof AppProfileRouteRoute
  '/roles': typeof AppRolesRouteRoute
  '/settings': typeof AppSettingsRouteRoute
  '/tenants': typeof AppTenantsRouteRoute
  '/users': typeof AppUsersRouteRoute
  '/': typeof AppIndexRoute
  '/dict/items': typeof AppDictItemsRoute
  '/dict': typeof AppDictIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/_app/depts': typeof AppDeptsRouteRoute
  '/_app/dict': typeof AppDictRouteRouteWithChildren
  '/_app/files': typeof AppFilesRouteRoute
  '/_app/gen': typeof AppGenRouteRoute
  '/_app/jobs': typeof AppJobsRouteRoute
  '/_app/logs': typeof AppLogsRouteRoute
  '/_app/menus': typeof AppMenusRouteRoute
  '/_app/messages': typeof AppMessagesRouteRoute
  '/_app/monitor': typeof AppMonitorRouteRoute
  '/_app/notices': typeof AppNoticesRouteRoute
  '/_app/online': typeof AppOnlineRouteRoute
  '/_app/params': typeof AppParamsRouteRoute
  '/_app/posts': typeof AppPostsRouteRoute
  '/_app/profile': typeof AppProfileRouteRoute
  '/_app/roles': typeof AppRolesRouteRoute
  '/_app/settings': typeof AppSettingsRouteRoute
  '/_app/tenants': typeof AppTenantsRouteRoute
  '/_app/users': typeof AppUsersRouteRoute
  '/_app/': typeof AppIndexRoute
  '/_app/dict/items': typeof AppDictItemsRoute
  '/_app/dict/': typeof AppDictIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/depts'
    | '/dict'
    | '/files'
    | '/gen'
    | '/jobs'
    | '/logs'
    | '/menus'
    | '/messages'
    | '/monitor'
    | '/notices'
    | '/online'
    | '/params'
    | '/posts'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/tenants'
    | '/users'
    | '/dict/items'
    | '/dict/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/depts'
    | '/files'
    | '/gen'
    | '/jobs'
    | '/logs'
    | '/menus'
    | '/messages'
    | '/monitor'
    | '/notices'
    | '/online'
    | '/params'
    | '/posts'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/tenants'
    | '/users'
    | '/'
    | '/dict/items'
    | '/dict'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/depts'
    | '/_app/dict'
    | '/_app/files'
    | '/_app/gen'
    | '/_app/jobs'
    | '/_app/logs'
    | '/_app/menus'
    | '/_app/messages'
    | '/_app/monitor'
    | '/_app/notices'
    | '/_app/online'
    | '/_app/params'
    | '/_app/posts'
    | '/_app/profile'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/tenants'
    | '/_app/users'
    | '/_app/'
    | '/_app/dict/items'
    | '/_app/dict/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tenants': {
      id: '/_app/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AppTenantsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/posts': {
      id: '/_app/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AppPostsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/params': {
      id: '/_app/params'
      path: '/params'
      fullPath: '/params'
      preLoaderRoute: typeof AppParamsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/online': {
      id: '/_app/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof AppOnlineRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notices': {
      id: '/_app/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AppNoticesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/monitor': {
      id: '/_app/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof AppMonitorRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/menus': {
      id: '/_app/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof AppMenusRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/gen': {
      id: '/_app/gen'
      path: '/gen'
      fullPath: '/gen'
      preLoaderRoute: typeof AppGenRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dict': {
      id: '/_app/dict'
      path: '/dict'
      fullPath: '/dict'
      preLoaderRoute: typeof AppDictRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/depts': {
      id: '/_app/depts'
      path: '/depts'
      fullPath: '/depts'
      preLoaderRoute: typeof AppDeptsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dict/': {
      id: '/_app/dict/'
      path: '/'
      fullPath: '/dict/'
      preLoaderRoute: typeof AppDictIndexRouteImport
      parentRoute: typeof AppDictRouteRoute
    }
    '/_app/dict/items': {
      id: '/_app/dict/items'
      path: '/items'
      fullPath: '/dict/items'
      preLoaderRoute: typeof AppDictItemsRouteImport
      parentRoute: typeof AppDictRouteRoute
    }
  }
}

interface AppDictRouteRouteChildren {
  AppDictItemsRoute: typeof AppDictItemsRoute
  AppDictIndexRoute: typeof AppDictIndexRoute
}

const AppDictRouteRouteChildren: AppDictRouteRouteChildren = {
  AppDictItemsRoute: AppDictItemsRoute,
  AppDictIndexRoute: AppDictIndexRoute,
}

const AppDictRouteRouteWithChildren = AppDictRouteRoute._addFileChildren(
  AppDictRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppDeptsRouteRoute: typeof AppDeptsRouteRoute
  AppDictRouteRoute: typeof AppDictRouteRouteWithChildren
  AppFilesRouteRoute: typeof AppFilesRouteRoute
  AppGenRouteRoute: typeof AppGenRouteRoute
  AppJobsRouteRoute: typeof AppJobsRouteRoute
  AppLogsRouteRoute: typeof AppLogsRouteRoute
  AppMenusRouteRoute: typeof AppMenusRouteRoute
  AppMessagesRouteRoute: typeof AppMessagesRouteRoute
  AppMonitorRouteRoute: typeof AppMonitorRouteRoute
  AppNoticesRouteRoute: typeof AppNoticesRouteRoute
  AppOnlineRouteRoute: typeof AppOnlineRouteRoute
  AppParamsRouteRoute: typeof AppParamsRouteRoute
  AppPostsRouteRoute: typeof AppPostsRouteRoute
  AppProfileRouteRoute: typeof AppProfileRouteRoute
  AppRolesRouteRoute: typeof AppRolesRouteRoute
  AppSettingsRouteRoute: typeof AppSettingsRouteRoute
  AppTenantsRouteRoute: typeof AppTenantsRouteRoute
  AppUsersRouteRoute: typeof AppUsersRouteRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDeptsRouteRoute: AppDeptsRouteRoute,
  AppDictRouteRoute: AppDictRouteRouteWithChildren,
  AppFilesRouteRoute: AppFilesRouteRoute,
  AppGenRouteRoute: AppGenRouteRoute,
  AppJobsRouteRoute: AppJobsRouteRoute,
  AppLogsRouteRoute: AppLogsRouteRoute,
  AppMenusRouteRoute: AppMenusRouteRoute,
  AppMessagesRouteRoute: AppMessagesRouteRoute,
  AppMonitorRouteRoute: AppMonitorRouteRoute,
  AppNoticesRouteRoute: AppNoticesRouteRoute,
  AppOnlineRouteRoute: AppOnlineRouteRoute,
  AppParamsRouteRoute: AppParamsRouteRoute,
  AppPostsRouteRoute: AppPostsRouteRoute,
  AppProfileRouteRoute: AppProfileRouteRoute,
  AppRolesRouteRoute: AppRolesRouteRoute,
  AppSettingsRouteRoute: AppSettingsRouteRoute,
  AppTenantsRouteRoute: AppTenantsRouteRoute,
  AppUsersRouteRoute: AppUsersRouteRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
